# 
#   Copyright (C) 2018 Philipp Paulweber, Simon Tragatschnig, and Patrick Gaubatz
#   All rights reserved.
# 
#   Developed by: Philipp Paulweber
#                 <https://github.com/ppaulweber/3iotBox>
# 
#   This file is part of 3iotBox.
# 
#   3iotBox is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
# 
#   3iotBox is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
# 
#   You should have received a copy of the GNU General Public License
#   along with 3iotBox. If not, see <http://www.gnu.org/licenses/>.
# 

* 3iotBox -- 3 IoT Complete Box

This project is an proof of concept implementation for a customer display to deliver electronic receipts.
The hardware is the "3IoT Complete" box provided by 3 Austria (Hutchison 3G Austria GmbH).
The fiscal middleware of [[https://obono.at][obono]] provides an implementation for the austrian regulation for cash registers (Registrierkassensicherheitsverordnung, RKSV) and electronic receipts. The documentation for the obono fiskal service can be found at [[https://demo.obono.at/api/v1/docs]].
The fiscal middleware is provided by [[https://codewerkstatt.at][CodeWerkstatt]].

** Copyright and License

The copyright holder of 
=3iotBox= is
Philipp Paulweber ([[https://github.com/ppaulweber][@ppaulweber]]), 
Simon Tragatschnig ([[https://github.com/tragatschnig][@tragatschnig]]), and
Patrick Gaubatz ([[https://github.com/pgaubatz][@pgaubatz]])
and the used license of 
=3iotBox= is the [[https://www.gnu.org/licenses/gpl-3.0.html][GNU GPLv3+]].

*** Notice

#+begin_src

Copyright (C) 2018 Philipp Paulweber, Simon Tragatschnig, and Patrick Gaubatz
All rights reserved.

Developed by: Philipp Paulweber
              <https://github.com/ppaulweber/3iotBox>

This file is part of 3iotBox.

3iotBox is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

3iotBox is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with 3iotBox. If not, see <http://www.gnu.org/licenses/>.

#+end_src
